services:
  - type: web
    name: Nexent Interactive (Website)
    runtime: static
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /talens
        destination: /talens/index.html
      - type: rewrite
        source: /liniastripes
        destination: /liniastripes/index.html
      - type: rewrite
        source: /liniasuper
        destination: /liniasuper/index.html
